# https://travis-ci.org/peterbe/premailer

language: python

python:
  - "2.7"

before_install:
    - pip install coverage

install:
  - python setup.py install

script:
  - nosetests premailer --with-cover --cover-erase --cover-package=premailer

after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls --use-mirrors
    - coveralls
